### ISSUE TITLE
잘못된 URL을 입력했을 경우 404 페이지로 Redirect + n초 후 첫 화면으로 이동

### ISSUE THREAD

**Issue by voidmatcha** [witherview/witherview_frontend#42]
## **Is your feature request related to a problem? Please describe.**
404 컴포넌트는 작성되어 있지만 react-router-dom을 통해 Redirect 되게끔 처리되지 않은 상태입니다. 이를 추가하고 404페이지에서 일정 시간(n초) 후에 첫 화면으로 이동하는 부분도 구현되면 유저 입장에서 좋다고 생각됩니다.

## **Describe the solution you'd like**
Redirect는 react-router-dom 공식 문서의 [no-macth](https://reactrouter.com/web/example/no-match
)를 기반으로 작업합니다. n초 후 첫화면으로 이동하는 부분은 setTimeout을 사용하여 작업합니다.

**Comment by wooooooood** [comment]
이 작업 제가 하겠습니다~
