### ISSUE TITLE
관심 산업 및 직무 태그 컴포넌트 제작 

### ISSUE THREAD

**Issue by voidmatcha** [witherview/witherview_frontend#43]
## **Is your feature request related to a problem? Please describe.**
<img width="433" alt="Screen Shot 2021-04-13 at 9 58 23 PM" src="https://user-images.githubusercontent.com/16266103/114556139-600d0380-9ca3-11eb-8b01-d90c4ce44807.png">

은비님이 디자인 수정한 부분 중 관심 산업 및 직무에 대한 태그를 컴포넌트로 제작해야 합니다.

## **Describe the solution you'd like**
[zeplin](https://app.zeplin.io/project/5f6de5b737ba5f49f5921a72/screen/5fd0bb3303bd7b489027148a)을 참고하여 확장성 및 용도에 맞게 컴포넌트를 제작합니다.

**Comment by wooooooood** [comment]
이 작업 제가 하고싶습니다~😀
assign이 없는것 같아서 셀프로 하겠습니다! ㅎㅎ
